### ISSUE TITLE
Add tooltip over charts, which works as links

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-gui#126]
Some of the charts are redirecting to different parts of the application, and currently after hovering over it the cursor will change to pointer (when #121 will be merged), but there is no information about where it will redirect us after the click.

Because it's not a "normal" HTML element, it should probably be implemented using functionality of the [amcharts](https://github.com/amcharts/amcharts4)

**Comment by tharun208** [comment]
@bartsmykla, I will pick this up

**Comment by bartsmykla** [comment]
@tharun208 please wait a day as I will introduce some change in the charts

**Comment by bartsmykla** [comment]
but thank you for picking this! :-)

**Comment by kleinfreund** [comment]
The status quo is this: hovering over a chart slice which has a URL (true for the zones and dp proxies charts currently, will add it for services and Zone CPs), data for that slice is shown in its label. It doesn’t directly indicate what the interaction will do, but since the current labels match the pages that are being linked to, I think it’s clear enough.

![image](https://user-images.githubusercontent.com/5774638/189294709-463114bd-c016-4086-871f-943ab240e953.png)

**Comment by kleinfreund** [comment]
**Triage**: This doesn’t seem relevant to do.
