### ISSUE TITLE
Improve list view filters

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#1415]
### Description

Improve the list view filters

- Better error state handling
- Making it more clear how to search for tags (the general syntax is `tag: 'kuma.io/service: service-1'`)
- search DPP by IP

**Comment by lahabana** [comment]
Might be worth following: https://kong-aip.netlify.app/aip/160/

**Comment by johncowen** [comment]
Summary of sync discussion:

As we can 'guess' information based on whether a search term has a `:` in it or not (due to DNS) we can say:

1. If the search term _doesn't_ have a `:` in it, then it is a `name` search.
2. If the search term has a `:` in it then we either:
    - Apply any "special" rules we have hardcoded into the frontend, a.k.a. "shortcut expansion" such as `zone:` > `kuma.io/zone:`
    - Assume that the search term is looking for a tag i.e. `version: 1` (which would be a "shortcut" for `tag: "version: 1"`)
3. If a user wants to specifically search for the tag `zone` (not as a shortcut for `kuma.io/zone:`) they would have to use `tag: "zone: zone.name"` specifically.

---

How this would work in practice:

- `name-of-dpp` would do a search based on name
- `version: 1` would do a search based on the tag `version` equalling `1`
- `kuma.io/zone: zone-name` would do a search based on the tag `kuma.io/zone` equalling `zone-name`
- `zone: zone-name` would be a "shortcut" that would expand to `kuma.io/zone` and use the same `kuma.io/zone: zone-name` tag search as the explained in the previous point.
- `status: degraded` _currently_ would search for a tag called `status` equalling `degraded`
- `status: degraded` _in a possible future_  could search for a dpp with the status _field_ as `degraded`. If you wanted to instead search by a `status` tag you would have to use the long form `tag: "status:degraded"`

---

We also discussed but discarded:

For "shortcut expansion" we could have used both the original tag shortcut and the expanded shortcut, i.e.

- `zone: zone-name` could perform a search for anything with the tags `kuma.io/zone: zone-name` _or_ `zone: zone-name`
- `status: degraded` could perform a search for anything with the tags `status: degraded` _or_ an entity with the field `status` equalling `degraded`

**Comment by kleinfreund** [comment]
> * Apply any "special" rules we have hardcoded into the frontend, a.k.a. "shortcut expansion" such as `zone:` > `kuma.io/zone:`

Small correction: the expansion is from `zone:...` to `tag: 'kuma.io/zone:...'` (i.e. a tag filter).

**Comment by johncowen** [comment]
Progress happening on this one over here https://github.com/kumahq/kuma-gui/pull/1721

**Comment by lahabana** [comment]
Superseeded by https://github.com/kumahq/kuma-gui/issues/3134
