### ISSUE TITLE
For provided gateway policies tab should request the same as regular DPP

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#1720]
### What happened?

Currently it does the same as builtin gateway. It should be the same as regular DPPs (policies + rules and output of the first is `SidecarDataplane`.

**Comment by kleinfreund** [comment]
@lahabana Are the following assumptions correct?

A `DataplaneOverview` represents a builtin gateway if `DataplaneOverview.dataplane.networking.gateway.type === 'BUILTIN'`.

A `DataplaneOverview` represents a delegated gateway in all other cases (i.e. `DataplaneOverview.dataplane.networking.gateway.type` is absent or a different value than `'BUILTIN'`).

I’m asking this because our types for the `type` field said `'builtin' | 'delegated' | undefined`, but from looking at some example files in the backend code, it looks like (1) the value is actually all uppercase and (2) it doesn’t necessarily have a `'DELEGATED'` value (I couldn’t find any actually).
