### ISSUE TITLE
Links to the policy list view shouldn't start at CircuitBreakers

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#2415]
### Description

For example clicking here:

<img width="1117" alt="Screenshot 2024-04-11 at 14 19 50" src="https://github.com/kumahq/kuma-gui/assets/554604/61ec072a-d03c-4e55-ab71-8b1268bec2c8">

Takes me here:

<img width="1424" alt="Screenshot 2024-04-11 at 14 20 39" src="https://github.com/kumahq/kuma-gui/assets/554604/ee29ef09-6d82-453d-8113-01bbeeb43bae">

When it should probably take me to either MeshCircuitBreaker (because: the first that has a non-zero amount), or MeshAccessLog (because: the first in the list)

**Comment by kleinfreund** [comment]
CircuitBreaker _used_ to be the first in the list which is why it was chosen. Now it should be MeshAccessLog. For the Policies tab (or links to the policy list view in general), we can’t link to the first one with non-zero policies because that would mean we’d always have to first evaluate `/mesh-insights/:mesh`.

**Comment by johncowen** [comment]
Closed by https://github.com/kumahq/kuma-gui/pull/2417 (must've used the wrong keyword for autoclose)
