### ISSUE TITLE
ProxyTemplates should be properly formatted

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma-gui#355]
### What happened?

ProxyTemplates are displayed all on one line without any line breaks or formatting when viewed in the UI

**Comment by kleinfreund** [comment]
I think we need to fix this on the API side. In the frontend, I could replace `\\n` with `<br>` to render new lines, but then the indentation would be way off because that information is lost to me:

![image](https://user-images.githubusercontent.com/5774638/187627042-75c0259a-7c6a-4979-863e-66fd95a19559.png)

**Comment by kleinfreund** [comment]
Currently, I’m considering the idea to turn instances like this into YAML multiline string literals like so:

**Current**:

![Screenshot from 2022-09-05 16-57-05](https://user-images.githubusercontent.com/5774638/188483349-7aa837fa-c22a-4b9f-a227-8c29e77e82a4.png)

**After**:

![Screenshot from 2022-09-05 16-56-01](https://user-images.githubusercontent.com/5774638/188483327-77c1f970-b710-4362-9ce4-8a8f718ab883.png)
