### ISSUE TITLE
Netlify previews don't work on Firefox

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-gui#363]
### What happened?

This is the issue happening from some time now, and when doing the review of upgrade to Vue.js 3 I realized we don't have an issue for it.

When trying to open the netlify preview in Firefox, I'm just seeing the white page
![image](https://user-images.githubusercontent.com/11655498/186079381-4d2fa30c-ad79-4dc0-a329-178b0516e380.png)

**Comment by kleinfreund** [comment]
The scenario in which this happens is if only Kuma GUI is running. If one starts Kuma and exposes http://localhost:5681 in the local network, this starts working.

I think the reason for this has to do with how msw (the library we use to mock requests in the local development server and the Netlify preview) intercepts network requests. In a context where the browser tries to enforce CORS (which Firefox does here), the preflight requests (e.g. `OPTIONS http://localhost:8080/policies`) doesn’t receive a positive response. I’m not sure how to fix this, but I think this is only a development issue because the GUI runs on the same origin in a real scenario, correct?

**Comment by bartsmykla** [comment]
Thank you @kleinfreund for looking at it. It's not bothering me that much that we HAVE to fix it and I'm even fine if we decide that fixes are to problematic, and can still just open chrome to work with netlifies previews. I'm fine with fetch, but if you think that axios brings more value then changing it would bring (handling cancellation etc.) I would leave it as is. :-)

**Comment by kleinfreund** [comment]
I actually quite like the idea of using plain fetch. We don’t do anything complicated with axios and even more advanced features (e.g. cancelling in-flight requests) are possible with fetch nowadays. I think that’s a worthwhile option that saves us another dependency.

**Comment by bartsmykla** [comment]
Let's go with it then :-D
