### ISSUE TITLE
Rework the way we depend on the gui from Kuma

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-gui#367]
### Description

We should have an easier and automated way for Kuma to get the latest GUI. We should also avoid having to build and checkin the whole UI in the Kuma repo

**Comment by kleinfreund** [comment]
## Now

Currently, Kuma GUI is updated in Kuma using https://github.com/kumahq/kuma/blob/master/mk/generate.mk#L109-L115 (i.e. check out the latest commit of kuma-gui, run `yarn install` and `yarn build`, and put the generated distribution files in the right place).

This means that as an objective, all that Kuma needs are the latest distribution files of Kuma GUI (latest could mean actually latest or a version referenced by a commit reference of some kind).

## Possible approach (rough draft)

**Upload distribution files on push to Kuma GUI’s default branch**

Instead of building the files in Kuma, we should build them whenever a push to Kuma GUI’s default branch happens (i.e. a PR is merged). Then, we can upload them to some kind of repository. This could be a simple `kuma-gui-latest.tar.gz` archive (alternatively named using a commit hash so we have a stable reference) of the `dist` directory or a built Docker image that’s uploaded to a Docker repository. This depends on how Kuma is actually bootstrapping the GUI. Would a Docker image even be useful here?

## Notes

- It’s probably sensible to upload distribution files with a commit hash (i.e. not with a generic latest name) so Kuma can decide to use an older version in case we need to fix an issue in the GUI but want to stop the bleeding more quickly.

**Comment by kleinfreund** [comment]
## Proposed solution

**Use a GitHub Action to create a PR in Kuma which updates a distribution files**

1. Create the distribution files (`yarn install`, `yarn build`).
2. Check-out Kuma’s default branch and prepare a pull request updating the distribution files.
3. Submit pull request.

In Kuma, an automatic process merges these PRs automatically.

Rollbacks would be done by rolling back changes in Kuma GUI.

**Comment by kleinfreund** [comment]
In https://github.com/kumahq/kuma/pull/4954, I’m removing the upgrade/gui command from Kuma. Besides that, this is now done so I’m closing this as done.
