### ISSUE TITLE
[BUG] broken URL in GUI

### ISSUE THREAD

**Issue by usrbinkat** [kumahq/kuma-gui#402]
### What happened?

# Problem
Guided GUI provides incorrect version in URI path.

URL displayed: https://kuma.io/docs/1.6.x/deployments/multi-zone/#zone-control-plane

### Expected
`1.6.x`

### Observed
`1.6.0`

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/54747391/194467322-dbb07370-62cf-40f0-9c77-f37958e11f2e.png">

**Comment by kleinfreund** [comment]
The following logic in the kuma.io repository automatically generates redirects for some of the cases like this:

https://github.com/kumahq/kuma-website/blob/master/docs/.vuepress/config.js#L384-L395

The following URLs redirect as expected:

- https://kuma.io/docs/1.6.2/deployments/multi-zone/#zone-control-plane
- https://kuma.io/docs/1.8.1/deployments/multi-zone/#zone-control-plane

For versions that aren’t discovered by this logic, there won’t be any redirects so a URL like https://kuma.io/docs/1.6.0/deployments/multi-zone/#zone-control-plane results in 404 because 1.6.0 is not a version for which a redirect would be created based on https://github.com/kumahq/kuma-website/blob/master/docs/docs/1.6.x/versions.json.

In the GUI, we can probably avoid this by always rewriting the patch version number to `x` for documentation URLs.
